from gpiozero import DigitalOutputDevice
from time import sleep

pinA = DigitalOutputDevice(5)
pinB = DigitalOutputDevice(6)
pinC = DigitalOutputDevice(13)
pinD = DigitalOutputDevice(12)
pinE = DigitalOutputDevice(17)
pinF = DigitalOutputDevice(27)
pinG = DigitalOutputDevice(22)
pinH = DigitalOutputDevice(23)


pinA.on()
pinB.on()
pinC.on()
pinD.on()
pinE.on()
pinF.on()
pinG.on()
pinH.on()
sleep(1)
pinA.off()
pinB.off()
pinC.off()
pinD.off()
pinE.off()
pinF.off()
pinG.off()
pinH.off()
pinA.on()
pinB.on()
pinC.on()
pinD.on()
pinE.on()
pinF.on()
pinG.on()
pinH.on()
sleep(1)
pinA.off()
pinB.off()
pinC.off()
pinD.off()
pinE.off()
pinF.off()
pinG.off()
pinH.off()